// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgt2nZAHLrikt6cvm4P1Wf1ZdJXEFRkdM',
    appId: '1:280621720311:web:dd0e4213651f6a7c60a9f2',
    messagingSenderId: '280621720311',
    projectId: 'crud-b1543',
    authDomain: 'crud-b1543.firebaseapp.com',
    storageBucket: 'crud-b1543.firebasestorage.app',
    measurementId: 'G-3RED1LW5CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplRxMlwNvoPJ3nVt8uPtDleUApa4FNUE',
    appId: '1:280621720311:android:fd617f36325e995060a9f2',
    messagingSenderId: '280621720311',
    projectId: 'crud-b1543',
    storageBucket: 'crud-b1543.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmH09Z4_dyb7stMy_2T0kbDCl-r8yrwQs',
    appId: '1:280621720311:ios:ef87865b3fb075c060a9f2',
    messagingSenderId: '280621720311',
    projectId: 'crud-b1543',
    storageBucket: 'crud-b1543.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );
}
